apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: velero-ui-ingress
  namespace: velero-ui
spec:
  ingressClassName: traefik
  rules:
  - host: velero.k8s.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: velero-ui
            port:
              number: 80