apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: velero-ui
metadata:
  name: velero-ui-kustomization

resources:
- service-account.yml
- roles.yml
- role-binding.yml
- cluster-role.yaml
- cluster-role-binding.yml
- configmap.yml
- deployment.yml
- service.yaml
- ingress.yaml