services:
  wexflow:
    image: aelassas/wexflow:latest
    container_name: wexflow
    restart: unless-stopped
    # SSL (optionals)
    # volumes:
    #   - ./wexflow_data/appsettings.json:/opt/wexflow/Wexflow.Server/appsettings.json:ro
    #   - ./wexflow_data/wexflow.pfx:/opt/wexflow/Wexflow.Server/wexflow.pfx:ro
    ports:
      - 8338:8000 # admin:wexflow2018
    #depends_on:
    #  - mongo

  # mongo:
  #   image: mongo:latest
  #   container_name: mongo
  #   restart: unless-stopped
  #   ports:
  #     - 27017:27017