scrape_configs:
  - job_name: jenkins
    metrics_path: /prometheus
    bearer_token: 1180f72a8cdb6eac2be7e3af10185c770a # http://192.168.3.105:8080/user/lifailon/security
    static_configs:
      - targets:
        - '192.168.3.105:8080'