apiVersion: apps/v1
kind: Deployment
metadata:
  name: dozzle
spec:
  selector:
    matchLabels:
      app: dozzle
  template:
    metadata:
      labels:
        app: dozzle
    spec:
      serviceAccountName: pod-viewer
      containers:
        - name: dozzle
          image: amir20/dozzle:latest
          ports:
            - containerPort: 8080
          env:
            - name: DOZZLE_MODE
              value: "k8s"
            # Auth
            - name: DOZZLE_AUTH_PROVIDER
              value: "simple"
          volumeMounts:
            - name: auth-config
              mountPath: /data/users.yml
              subPath: users.yml
              readOnly: true
      volumes:
        - name: auth-config
          secret:
            secretName: dozzle-auth-secret