apiVersion: v1
kind: Secret
metadata:
  name: dozzle-auth-secret
type: Opaque
stringData:
  users.yml: |
    users:
      admin:
        name: "admin"
        password: "a800c3ee4dac5102ed13ba673589077cf0a87a7ddaff59882bb3c08f275a516e"