apiVersion: v1
kind: Service
metadata:
  name: dozzle-service
  annotations:
    metallb.universe.tf/address-pool: "default-pool"
    metallb.universe.tf/loadBalancerIPs: "192.168.3.202"
spec:
  type: LoadBalancer
  selector:
    app: dozzle
  ports:
    - port: 4477
      targetPort: 8080
      protocol: TCP