apiVersion: v1
kind: Service
metadata:
  name: dozzle-service
spec:
  type: NodePort
  selector:
    app: dozzle
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30002