apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: diun
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/Lifailon/PS-Commands
    path: Kubernetes/diun
    targetRevision: rsa
    helm:
      values: ''
      valueFiles:
        - values.yaml
      parameters:
        - name: secrets.telegram.id
          value: test
        - name: secrets.telegram.token
          value: test
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true