apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dozzle
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    path: Kubernetes/dozzle
    repoURL: https://github.com/Lifailon/rudocs
    targetRevision: rsa
  sources: []
  project: default
  syncPolicy:
    automated: null
