apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/traefik/traefik-helm-chart
    path: traefik
    targetRevision: master
    helm:
      # https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
      valueFiles:
        - values.yaml
      values: |-
        service:
          type: LoadBalancer
          annotations:
            metallb.universe.tf/address-pool: "default-pool"
      parameters:
        - name: ingressRoute.dashboard.enabled
          value: 'true'
        - name: ports.traefik.port
          value: '8080'
        - name: ports.traefik.exposedPort
          value: '8888'
        - name: ports.traefik.hostPort
          value: '30005'
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated: null