apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
spec:
  destination:
    namespace: kubernetes-dashboard
    server: https://kubernetes.default.svc
  source:
    path: Kubernetes/headlamp
    repoURL: https://github.com/Lifailon/PS-Commands
    targetRevision: rsa
  sources: []
  project: default
  syncPolicy:
    automated: null
