services:
  telegram-downloader:
    image: tangyoha/telegram_media_downloader:latest
    container_name: telegram-downloader
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - ./downloads:/app/downloads
      - ./config.yaml:/app/config.yaml
      - ./data.yaml:/app/data.yaml
      - ./log/:/app/log/
      - ./sessions/:/app/sessions
      - ./temp/:/app/temp