entryPoints:
  # HTTPS redirect
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls: {}
    transport:
      keepAliveMaxRequests: 0
      respondingTimeouts:
        idleTimeout: "30m"
  traefik:
    address: ":8080"
  metrics:
    address: ":4318"

# Dashboard
api:
  dashboard: true
  insecure: true

# Healthcheck endpoint
ping:
  terminatingStatusCode: 204

# Jaeger tracing
# tracing:
#   serviceName: traefik
#   otlp:
#     grpc:
#       endpoint: jaeger:4317
#       insecure: true

# Prometheus Exporter endpoint
metrics:
  prometheus:
    entryPoint: metrics
    addRoutersLabels: true
    addServicesLabels: true

# Log format
log:
  format: "common"  # common or json
  level: "INFO"     # DEBUG, INFO, WARN, ERROR, FATAL and PANIC

# Access log filters
accessLog:
  format: "common"
  filters:
    minDuration: "1ms"
    statusCodes:
      - "200-299"
      - "300-399"
      - "400-499"
      - "500-599"

# Sources
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true
    # Default rule format for compose: <service_name>-<project_name>
    # defaultRule: "Host(`{{ .Name }}.docker.local`)"
    # Template format for index function: index <map> <key>
    defaultRule: "Host(`{{ index .Labels \"com.docker.compose.service\" | default .Name }}.docker.local`)"
  file:
    directory: /rules
    watch: true

# Sablier plugin
experimental:
  plugins:
    sablier:
      moduleName: "github.com/sablierapp/sablier-traefik-plugin"
      version: "v1.1.0"