apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring
metadata:
  name: gatus-kustomization

resources:
# - configmap.yaml
- service-account.yaml
- deployment.yaml
- service.yaml

configMapGenerator:
- name: gatus-config
  files:
    - config.yaml