apiVersion: v1
kind: Service
metadata:
  name: gatus-service
  namespace: monitoring
  annotations:
    metallb.universe.tf/address-pool: "default-pool"
    metallb.universe.tf/loadBalancerIPs: "192.168.3.205"
spec:
  # Открываем доступ через адрес 192.168.3.205:80 и nodeIP:30050
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30050
      protocol: TCP
  selector:
    app: gatus