services:
  OpenRouter-Telegram-Bot:
    container_name: OpenRouter-Telegram-Bot
    image: lifailon/openrouter-telegram-bot:latest
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .env:/bot/.env
    restart: unless-stopped
