services:
  pinguem:
    image: lifailon/pinguem:latest
    container_name: pinguem
    restart: unless-stopped
    ports:
      - 8085:8085 # Fronend (WebUI)
      - 3005:3005 # Backend (API)

  statping:
    image: dockurr/statping
    container_name: statping
    restart: unless-stopped
    stop_grace_period: 1m
    ports:
      - 8001:8080
    volumes:
      - ./statping_data:/app

  smokeping:
    image: lscr.io/linuxserver/smokeping:latest
    container_name: smokeping
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC+3
      - MASTER_URL=https://smokeping.docker.local/smokeping/
      - SHARED_SECRET=password
      - CACHE_DIR=/tmp
    volumes:
      - ./smokeping_conf:/config
      - ./smokeping_data:/data
    ports:
      - 8000:80