services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    restart: unless-stopped
    ports:
      - "8500:8500"
    command: "agent -server -bootstrap-expect=1 -client=0.0.0.0"
    volumes:
      - ./consul_data:/consul/data
      - ./consul.hcl.config:/consul/config/consul.hcl

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: unless-stopped
    depends_on:
      - consul
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://localhost:8200
    ports:
      - "8200:8200"
    volumes:
      - ./vault_config:/vault/config
      # Использовать локальное файловое хранилище
      # - ./vault_data:/vault/file
    cap_add:
      - IPC_LOCK
    command: >
      vault server -config=/vault/config/vault.hcl
