version: '3'
services:
  isaiah:
    image: mosswill/isaiah:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      SERVER_ROLE: "Agent"
      AUTHENTICATION_SECRET: "secret"
      MASTER_HOST: "192.168.3.105:5052"
      MASTER_SECRET: "secret"
      AGENT_NAME: "rpi-105"