apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: telegram

resources:
# - configmap.yaml
- deployment.yaml

configMapGenerator:
- name: openrouter-bot-config
  # Передать содержимое файла в configMap
  files:
    - .env
  # Определить переменные окружения вручную (- key=value)
  # literals:
  #   - LOG_MODE=DEBUG
  # Определить переменные окружения из env файла
  # envs:
  #   - .env