services:
  go-playground:
    # dev image
    # image: ghcr.io/x1unix/go-playground/go-playground:latest
    image: x1unix/go-playground:latest
    container_name: go-playground
    restart: unless-stopped
    ports:
      - 9096:8000
    environment:
      APP_CLEAN_INTERVAL: '30m'