apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headlamp-ingress
  namespace: monitoring
spec:
  ingressClassName: traefik
  rules:
  - host: headlamp.k8s.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: headlamp-service
            port:
              number: 80