apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: headlamp-kustomization

resources:
- namespace.yaml
- service-account.yaml
- cluster-role-binding.yaml
- secret.yaml
- deployment.yaml
- service.yaml