kind: Service
apiVersion: v1
metadata:
  name: headlamp
  namespace: kubernetes-dashboard
  annotations:
    metallb.universe.tf/address-pool: "default-pool"
    metallb.universe.tf/loadBalancerIPs: "192.168.3.201"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 4466
      nodePort: 30002
  selector:
    k8s-app: headlamp