services:
  cronicle:
    image: soulteary/cronicle:0.9.80
    container_name: cronicle
    restart: always
    ports:
      - 3012:3012
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./cronicle_data/data:/opt/cronicle/data
      - ./cronicle_data/logs:/opt/cronicle/logs
      - ./cronicle_data/plugins:/opt/cronicle/plugins
      - /home/lifailon/docker:/backup
    environment:
      - TZ=Etc/UTC+3