services:
  keeweb:
    container_name: keeweb
    image: ghcr.io/keeweb/keeweb:latest       # Github image
    # image: keeweb/keeweb:latest             # Dockerhub image
    restart: unless-stopped
    volumes:
      - ./cert.crt:/config/keys/cert.crt:ro
      - ./cert.key:/config/keys/cert.key:ro
      - ./keeweb:/config
    ports:
      - 4343:443
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
