- resources:
    cpu: true
    memory: true
    disk:
      - /
    cputemp: true
    units: metric
    tempmin: 0
    tempmax: 80
    refresh: 3000
    diskUnits: bytes
    network: true
    uptime: true

- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: "cluster"
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true

# - glances:
#     url: http://192.168.3.101:61208
#     username: admin
#     password: admin
#     version: 4
#     cpu: true
#     mem: true
#     cputemp: true
#     uptime: true
#     disk: /
#     diskUnits: bytes
#     expanded: true
#     label: node-01

# - search:
#     provider: custom
#     url: https://yandex.ru/search/?text=

- openmeteo:
    label: MSK
    latitude: 55.45
    longitude: 37.37
    units: metric
    cache: 10

- datetime:
    text_size: xl
    format:
      timeStyle: short
      hourCycle: h23