apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-auth
  namespace: default
spec:
  basicAuth:
    secret: traefik-creds
---
# htpasswd -nbB admin admin | base64
apiVersion: v1
kind: Secret
metadata:
  name: traefik-creds
  namespace: default
type: Opaque
data:
  users: |2
    YWRtaW46JDJ5JDA1JGMwcjVBNlNDS1g0UjZGanVDZ1JxcnVmYklFNXRtWHcyc0RQcTF2Wjh6TnJy
    d05aSUg5amdXCgo=