apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  # Traefik Dashboard
  - match: Host(`traefik.k8s.local`)
    kind: Rule
    services:
      - name: api@internal
        kind: TraefikService
    # Auth for Dashboard
    middlewares:
      - name: traefik-auth
  # Traefik Prometheus Metrics
  - match: Host(`traefik-metrics.k8s.local`)
    kind: Rule
    services:
      - name: prometheus@internal
        kind: TraefikService