server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki-server:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job_name: system
          node_name: hv-us-01
          __path__: /var/log/*log
    pipeline_stages:
      - regex:
          expression: "^/var/log/(?P<file_name>.+)$"
          source: filename
      - labels:
          file_name:

  - job_name: docker
    # static_configs:
    #   - targets:
    #       - localhost
    #     labels:
    #       job_name: docker
    #       __path__: /var/lib/docker/containers/*/*.log
    # pipeline_stages:
    #   - json:
    #       expressions:
    #         log: log
    #         stream: stream
    #         time: time
    #   - regex:
    #       expression: "^/var/lib/docker/containers/(?P<container_id>.{12}).+/.+-json.log$"
    #       source: filename
    #   - timestamp:
    #       format: RFC3339Nano
    #       source: time
    #   - labels:
    #       stream:
    #       container_id:
    #   - output:
    #       source: log
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - target_label: job_name
        replacement: docker
      - target_label: node_name
        replacement: hv-us-01
      - source_labels: [__meta_docker_container_name]
        target_label: container_name
        replacement: $1
        action: replace
        regex: /?(.*)
      - source_labels: [__meta_docker_container_log_path]
        target_label: __path__
    pipeline_stages:
      - json:
          expressions:
            level:
      # - regex:
      #     expression: '(?P<level>INFO|WARN|WARNING|ERR|ERRO|ERROR):'    # INFO:
      # - regex:
      #     expression: '\[(?P<level>INFO|WARN|WARNING|ERR|ERRO|ERROR)\]' # [INFO]
      - regex:
          expression: '\[(?P<tag>[A-Za-z]+)\]'                            # [TEXT]
      - labels:
          level:
          tag: