global:
  scrape_interval: 10s
  scrape_timeout: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "alert.yml"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - prometheus:9090

  # Linux
  - job_name: node
    static_configs:
      - targets:
        - node-exporter:9100
        - 192.168.3.106:9100

  # Windows
  - job_name: ohmgraphite
    static_configs:
      - targets:
        - 192.168.3.100:4445

  # Docker
  - job_name: cadvisor
    static_configs:
      - targets:
        - cadvisor:8080
        - 192.168.3.106:9333

  - job_name: logporter
    scrape_interval: 10s
    scrape_timeout: 10s
    static_configs:
      - targets:
        - logporter:9333
        - 192.168.3.106:9333

  # Go App
  # - job_name: go-app
  #   static_configs:
  #     - targets:
  #       - 192.168.3.100:2112

  # Speedtest
  - job_name: speedtest-exporter
    scrape_interval: 15m
    scrape_timeout: 90s
    static_configs:
      - targets:
        - 192.168.3.105:9798

  # CI/CD
  - job_name: jenkins
    metrics_path: /prometheus
    bearer_token: 1180f72a8cdb6eac2be7e3af10185c770a
    static_configs:
      - targets:
        - 192.168.3.105:8080

  # REST API
  - job_name: gatus
    static_configs:
      - targets:
          - 192.168.3.105:8081

  # - job_name: uptime-kuma
  #   scrape_interval: 30s
  #   static_configs:
  #     - targets:
  #       - 192.168.3.105:8081
  #   basic_auth:
  #     password: uk1_fl3JxkSDwGLzQuHk2FVb8z89SCRYq0_3JbXsy73t

# docker-compose kill -s SIGHUP prometheus