global:
  scrape_interval: 10s
  scrape_timeout: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "alert.yml"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - prometheus:9090

  # Linux
  - job_name: linux-node-exporter
    static_configs:
      - targets:
        - node-exporter:9100

  # Docker
  - job_name: logporter
    scrape_interval: 5s
    scrape_timeout: 1s
    static_configs:
      - targets:
        - logporter:9333

  # ICMP
  - job_name: blackbox-icmp
    metrics_path: /probe
    params:
      module: [icmp_ping]
    static_configs:
      - targets:
          - 8.8.8.8
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  # HTTPS
  - job_name: blackbox-http
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://google.com
          - https://telegram.org
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115