global:
  scrape_interval: 10s
  scrape_timeout: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "alert.yml"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - prometheus:9090

  # Linux
  - job_name: node
    static_configs:
      - targets:
        - node-exporter:9100

  # Docker
  - job_name: logporter
    scrape_interval: 5s
    scrape_timeout: 1s
    static_configs:
      - targets:
        - logporter:9333