services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - DOMAIN=http://vault.local:1338
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=1338
    volumes:
      - ./vw_data/:/data/
    # network_mode: host
    ports:
      - 1338:1338