apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
  # - 192.168.3.201/32
  - 192.168.3.201-192.168.3.210
  autoAssign: false # требует аннотации пула и указания адреса в service

# kind: Service
# apiVersion: v1
# metadata:
#   name: headlamp
#   namespace: kubernetes-dashboard
#   annotations:
#     metallb.universe.tf/address-pool: "default-pool"
#     metallb.universe.tf/loadBalancerIPs: "192.168.3.201"