apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system
metadata:
  name: metallb-kustomization

resources:
- crd.yaml
- webhook.yaml
- service-account.yaml
- roles.yaml
- role-binding.yaml
- configmap.yaml
- deployment.yaml
- daemon-set.yaml
- service.yaml
- metrics-ingress.yaml
- metrics-middleware.yaml
- ip-address-pool.yaml
- l2-advertisement.yaml