apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system
metadata:
  name: metallb-kustomization

resources:
- deployment.yaml
- ip-address-pool.yaml
- l2-advertisement.yaml