# mkdir database/ settings/ && chown -R 1000:1000 database/ settings/

services:
  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    ports:
      - 8888:80
    volumes:
      - /home/lifailon:/srv   # root directory
      - ./database:/database  # filebrowser.db
      - ./settings:/config    # settings.json
    user: 1000:1000
    restart: unless-stopped

# login: admin
# password from docker logs file-browser
# Randomly generated password for user 'admin': u71Dlf8Bi812CFgi