services:
  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    ports:
      - "8888:80"
    volumes:
      - /home/lifailon:/srv
      # Предварительно создать файл бд или Docker создаст директорию
      # touch ./filebrowser.db
      - ./filebrowser.db:/database.db
      - ./filebrowser.json:/.filebrowser.json
    user: "1000:1000"
    restart: unless-stopped

# login: admin
# password from docker logs file-browser
# Randomly generated password for user 'admin': u71Dlf8Bi812CFgi