apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system
metadata:
  name: ksm-kustomization

resources:
- service-account.yaml
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- service.yaml