apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: kube-system
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.16.0
spec:
  type: NodePort
  ports:
    - name: http-metrics
      port: 80
      targetPort: 8080
      nodePort: 30002
    - name: telemetry
      port: 81
      targetPort: 8081
      nodePort: 30003
  selector:
    app.kubernetes.io/name: kube-state-metrics