server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.3.105:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job_name: system
          node_name: rpi-106
          __path__: /var/log/*log
    pipeline_stages:
      - regex:
          expression: "^/var/log/(?P<file_name>.+)$"
          source: filename
      - labels:
          file_name:

  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - target_label: job_name
        replacement: docker
      - target_label: node_name
        replacement: rpi-106
      - source_labels: [__meta_docker_container_name]
        target_label: container_name
        replacement: $1
        action: replace
        regex: /?(.*)
      - source_labels: [__meta_docker_container_log_path]
        target_label: __path__
    pipeline_stages:
      - json:
          expressions:
            level:
      - regex:
          expression: '\[(?P<tag>[A-Za-z]+)\]'
      - labels:
          level:
          tag: