services:
  cloud-torrent:
    image: jpillora/cloud-torrent
    container_name: cloud-torrent
    restart: unless-stopped
    ports:
      - "3010:3000"
    volumes:
      # Директория для загрузки в хостовой системе (WSL) : контейнер
      - /mnt/d/plex-content:/downloads