services:
  open-speedtest:
    image: openspeedtest/latest:latest
    container_name: opens-peedtest
    restart: unless-stopped
    # environment:
    #   - ENABLE_LETSENCRYPT=True
    #   - DOMAIN_NAME=speedtest.domain.com
    #   - USER_EMAIL=name@domain.com
    ports:
      - 3000:3000
      - 3001:3001