apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma-service
  namespace: monitoring
  annotations:
    metallb.universe.tf/address-pool: "default-pool"
    metallb.universe.tf/loadBalancerIPs: "192.168.3.206"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3001
      nodePort: 30060
      protocol: TCP
  selector:
    app: uptime-kuma