services:
  kan-web:
    image: ghcr.io/kanbn/kan:latest
    container_name: kan-web
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      # Авторизация доступна только через доменное имя
      - NEXT_PUBLIC_BASE_URL=http://kan.docker.local
      - BETTER_AUTH_SECRET=KanBanAdminSecret
      - POSTGRES_URL=postgresql://kan:KanBanAdminSecret@kan-db:5432/kan_db
      - NEXT_PUBLIC_ALLOW_CREDENTIALS=true
    depends_on:
      kan-db:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.kan-web.rule=Host(`kan.docker.local`)
      - traefik.http.services.kan-web.loadbalancer.server.port=3000

  kan-db:
    image: postgres:15
    container_name: kan-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: kan_db
      POSTGRES_USER: kan
      POSTGRES_PASSWORD: KanBanAdminSecret
    volumes:
      - ./kanban_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U planka -d planka"]
      interval: 5s
      timeout: 5s
      retries: 10