apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beszel-pvc
spec:
  # storageClassName: local-path
  storageClassName: longhorn
  accessModes:
    # - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi