apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beszel-pvc
spec:
  # storageClassName: local-path
  storageClassName: longhorn
  accessModes:
    # - ReadWriteOnce # подключен к одной ноде в режиме чтения-записи
    # - ReadOnlyMany # подключен к многим нодам в режиме только на чтение
    - ReadWriteMany # подключен к многим нодам в режиме чтения-записи
  resources:
    requests:
      storage: 1Gi