apiVersion: v1
kind: Service
metadata:
  name: beszel-service
  annotations:
    metallb.universe.tf/address-pool: "default-pool"
    metallb.universe.tf/loadBalancerIPs: "192.168.3.204"
spec:
  type: LoadBalancer
  selector:
    app: beszel-server
  ports:
    - port: 80
      targetPort: 8090
      nodePort: 30090