apiVersion: v1
kind: Secret
metadata:
  name: diun-secret
  namespace: default
type: Opaque
data:
  DIUN_NOTIF_TELEGRAM_TOKEN: {{ .Values.secrets.telegram.token | b64enc }}
  DIUN_NOTIF_TELEGRAM_CHATIDS: {{ toString .Values.secrets.telegram.id | b64enc }}