services:
  4gaBoards:
    image: ghcr.io/rargames/4gaboards:latest
    container_name: 4gaBoards
    restart: always
    networks:
      - boards-network
    environment:
      BASE_URL: http://localhost:1337
      SECRET_KEY: notsecretkey
      DATABASE_URL: postgresql://postgres:postgres@4gaBoards-db/4gaBoards
      NODE_ENV: production
      DEFAULT_ADMIN_USERNAME: "admin"
      DEFAULT_ADMIN_EMAIL: "admin@admin.com"
      DEFAULT_ADMIN_NAME: "Admin"
      DEFAULT_ADMIN_PASSWORD: "admin"
    depends_on:
      4gaBoards-db:
        condition: service_healthy
    volumes:
      - user-avatars:/app/public/user-avatars
      - project-background-images:/app/public/project-background-images
      - attachments:/app/private/attachments
    ports:
      - 1337:1337

  4gaBoards-db:
    image: postgres:16-alpine
    container_name: 4gaBoards-db
    restart: always
    networks:
      - boards-network
    volumes:
      - ./4gaBoards-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 4gaBoards
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: '-A scram-sha-256'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d 4gaBoards']
      interval: 1s
      timeout: 5s
      retries: 50

volumes:
  user-avatars:
  project-background-images:
  attachments:

networks:
  boards-network:
