services:
  postgresql:
    image: postgres
    container_name: postgresql
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U pgweb -h 127.0.0.1
      interval: 5s

  # Web UI Client
  pgweb:
    container_name: pgweb
    image: sosedoff/pgweb:latest
    build: .
    environment:
      PGWEB_DATABASE_URL: postgres://dbuser:dbpass@postgresql:5432/dbname?sslmode=disable
    ports:
      - 5443:8081
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "8081"]
      interval: 5s
    depends_on:
      postgresql:
        condition: service_healthy

  # Performance Dashboard for PostgreSQL
  pghero:
    image: ankane/pghero
    container_name: pghero
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://user:pass@postgresql:5432/dbname
    ports:
      - 5444:8080
    tty: true
    stdin_open: true

  # Web UI for PostgreSQL Backup
  postgresus:
    image: rostislavdugin/postgresus:latest
    container_name: postgresus
    restart: unless-stopped
    ports:
      - 5445:4005
    volumes:
      - ./postgresus-data:/postgresus-data
    depends_on:
      - postgresql

  # Cron job for PostgreSQL Backup
  pg-backup:
    image: kartoza/pg-backup:latest
    container_name: pg-backup
    restart: unless-stopped
    volumes:
      - db-backups:/backups
    environment:
      - DUMPPREFIX=PG
      - POSTGRES_HOST=postgresql
      - POSTGRES_USER=root
      - POSTGRES_PASS=root
      - POSTGRES_PORT=5432
      - RUN_AS_ROOT=true
      - CRON_SCHEDULE="*/5 * * * *"
      - CONSOLE_LOGGING=TRUE
      # S3
      # - STORAGE_BACKEND=S3
      # - ACCESS_KEY_ID=minio_admin
      # - SECRET_ACCESS_KEY=secure_minio_secret
      # - DEFAULT_REGION=us-west-2
      # - BUCKET=pg_backups
      # - HOST_BASE=minio:9000
      # - HOST_BUCKET=backup
      # - SSL_SECURE=False
    depends_on:
      postgresql:
        condition: service_healthy

  # REST API
  postgrest:
    image: postgrest/postgrest:latest
    container_name: postgrest
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      PGRST_DB_URI: postgres://dbuser:dbpass@postgresql:5432/dbname
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
    depends_on:
      - postgresql

  # Swagger UI for PostgREST
  postgrest-swagger:
    image: swaggerapi/swagger-ui:latest
    container_name: postgrest-swagger
    restart: unless-stopped
    ports:
      - 3001:8080
    expose:
      - 8080
    environment:
      API_URL: http://localhost:3000/
    depends_on:
      - postgresql
      - postgrest

  # REST API
  prest:
    image: prest/prest:latest
    container_name: prest
    restart: unless-stopped
    environment:
      - PREST_DEBUG=true
      - PREST_PG_HOST=postgres
      - PREST_PG_CACHE=false
      - PREST_JWT_DEFAULT=false
      - PREST_CACHE_ENABLED=false
    ports:
      - 3000:3000
    depends_on:
      postgresql:
        condition: service_healthy