services:
  scrypted:
    image: ghcr.io/koush/scrypted
    container_name: scrypted
    restart: unless-stopped
    volumes:
      - ./scrypted_volume:/server/volume
    devices: []
    network_mode: host # http://ip:11080 or https://ip:10443
    dns:
      - 1.1.1.1
      - 8.8.8.8
    logging:
      driver: json-file
      options:
          max-size: 10m
          max-file: 5