apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-bot-config
  namespace: telegram

data:
  .env: |
    TELEGRAM_BOT_TOKEN=
    TELEGRAM_USER_ID=
    WIN_SHELL=pwsh
    LINUX_SHELL=bash
    PARALLEL_EXEC=true
    SSH_PORT=2121
    SSH_USER=lifailon
    SSH_PASSWORD=
    SSH_PRIVATE_KEY_PATH=/root/.ssh/id_rsa
    SSH_CONNECT_TIMEOUT=2
    SSH_SAVE_ENV=true
    SSH_HOST_LIST=192.168.3.101,root@192.168.3.102:22,root@192.168.3.103:22,192.168.3.105,192.168.3.106
    LOG_MODE=DEBUG