apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-bot
  namespace: telegram
  labels:
    app: ssh-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssh-bot
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ssh-bot
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: [ssh-bot]
            topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 30
      containers:
      - image: lifailon/ssh-bot:latest
        name: ssh-bot
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        readinessProbe:
          exec:
            command: ["pgrep", "-f", "ssh-bot"]
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          exec:
            command: ["pgrep", "-f", "ssh-bot"]
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: ssh-config-volume   # Имя тома (должно совпадать с volumes:)
          mountPath: /ssh-bot/.env  # Куда монтировать в контейнере
          subPath: .env             # Какой файл из тома использовать для указанного пути
        - name: ssh-key-volume
          mountPath: /root/.ssh/id_rsa
          subPath: id_rsa
          readOnly: true
      volumes:
      - name: ssh-config-volume     # Имя тома, используемое для монтирования
        configMap:
          name: ssh-bot-config      # Имя configMap (объект в namespace)
          items:
          - key: .env
            path: .env
      - name: ssh-key-volume
        secret:
          secretName: ssh-bot-secrets
          items:
          - key: id_rsa
            path: id_rsa