apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: telegram

resources:
# - configmap.yaml
# - secrets.yaml
- deployment.yaml

configMapGenerator:
- name: ssh-bot-config
  files:
    - .env

secretGenerator:
- name: ssh-bot-secrets
  type: Opaque
  files:
    - id_rsa