services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/GMT+3
    volumes:
      - ./config/jackett:/config
      - ./torrent:/downloads      # blackhole - директория хранения торрент файлов (синхронизация с Transmission)
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - tor-network

  # nginx-proxy:
  #   image: nginx:latest
  #   container_name: nginx-proxy
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx.crt:/etc/nginx/ssl/nginx.crt
  #     - ./nginx.key:/etc/nginx/ssl/nginx.key
  #   networks:
  #     - tor-network
  #   restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/GMT+3
      - USER=admin
      - PASS=admin
    volumes:
      - ./config/transmission:/config
      - ./content:/downloads      # директория для хранения загруженных файлов (синхронизация с Jellyfin)
      - ./torrent:/watch          # директория для отслеживания торрент файлов на загрузку (синхронизация с Jackett)
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    networks:
      - tor-network

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/GMT+3
    volumes:
      - ./config/jellyfin:/config
      - ./content:/data/tvshows   # директория для хранения загруженных файлов (синхронизация с Transmission)
      - ./content:/data/movies
    ports:
      - 8096:8096                 # Веб интерфейс
      - 7359:7359/udp             # позволяет клиентам найти сервер Jellyfin в локальной сети (опционально)
      - 1900:1900/udp             # обнаружение служб используемых DNLA (опционально)
    restart: unless-stopped
    networks:
      - tor-network

networks:
  tor-network:
    driver: bridge