services:
  keeweb:
    container_name: keeweb
    image: ghcr.io/keeweb/keeweb:latest
    # image: keeweb/keeweb:latest
    restart: unless-stopped
    volumes:
      - ./cert.crt:/config/keys/cert.crt:ro
      - ./cert.key:/config/keys/cert.key:ro
      - ./keeweb_data:/config
    ports:
      - 4343:443
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
