services:
  iperf-server:
    image: alpine:latest
    container_name: iperf-server
    restart: unless-stopped
    command: >
      sh -c "
        apk add --no-cache iperf3 &&
        exec iperf3 -s -p $$PORT
      "
    environment:
      - PORT=5201
    ports:
      - 5201:5201