services:
  h5ai:
    image: awesometic/h5ai
    container_name: h5ai
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Etc/GMT+3"
      HTPASSWD: "true"
      HTPASSWD_USER: "awesometic"
      HTPASSWD_PW: "awesometic"
    restart: unless-stopped
    volumes:
      - ./data:/h5ai
      - ./conf:/config
    ports:
      - "9097:80"
