services:
  wekan:
    image: ghcr.io/wekan/wekan:latest
    container_name: wekan-app
    restart: unless-stopped
    environment:
      - ROOT_URL=https://wekan.docker.local
      - WRITABLE_PATH=/data
      - MONGO_URL=mongodb://wekan-db:27017/wekan
      - WITH_API=true
      - RICHER_CARD_COMMENT_EDITOR=false
      - CARD_OPENED_WEBHOOK_ENABLED=false
      - BIGEVENTS_PATTERN=NONE
      - BROWSER_POLICY_ENABLED=true
      - LDAP_BACKGROUND_SYNC_INTERVAL=''
    depends_on:
      - wekan-db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./wekan_data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.wekan.rule=Host(`wekan.docker.local`)
      - traefik.http.services.wekan.loadbalancer.server.port=8080
    # ports:
    #   - 8080:8080

  wekan-db:
    image: mongo:7
    container_name: wekan-db
    restart: unless-stopped
    command: mongod --logpath /dev/null --oplogSize 128 --quiet
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./wekan_db:/data/db
      - ./wekan_dump:/dump
    expose:
      - 27017
    # ports:
    #   - 27017:27017