services:
  dnsmasq:
    image: dockurr/dnsmasq
    container_name: dnsmasq
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - 53:53/udp
      - 53:53/tcp
    environment:
      DNS1: 1.0.0.1
      DNS2: 1.1.1.1