services:
  libre-speedtest:
    image: lscr.io/linuxserver/librespeed:latest
    container_name: libre-speedtest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/GMT+3
      - PASSWORD=PASSWORD # пароль для базы данных результатов
      - CUSTOM_RESULTS=true # опционально, включить пользовательскую страницу результатов в /config/www/results/index.php
      # - DB_TYPE=sqlite # по умолчанию sqlite (доступно mysql и postgresql)
      # - DB_NAME=DB_NAME # опционально, имя базы данных (требуется для mysql и pgsql)
      # - DB_HOSTNAME=DB_HOSTNAME # опционально
      # - DB_USERNAME=DB_USERNAME # опционально
      # - DB_PASSWORD=DB_PASSWORD # опционально
      # - DB_PORT=DB_PORT # опционально
      # - IPINFO_APIKEY=ACCESS_TOKEN # опционально, токен доступа от ipinfo.io (требуется для подробной информации об ip)
    volumes:
      - ./librespeed/config:/config
    ports:
      - 8088:80